# Generated by Django 2.2.9 on 2020-04-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_auto_20200423_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stage',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='modality',
            name='status',
        ),
        migrations.AlterField(
            model_name='results',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_athletes', to='jogos.Athlete'),
        ),
        migrations.AlterField(
            model_name='results',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_modality', to='jogos.Modality'),
        ),
        migrations.AlterField(
            model_name='results',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_stage', to='jogos.Stage'),
        ),
        migrations.AlterField(
            model_name='results',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AddField(
            model_name='stage',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_modality', to='jogos.Modality'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('modality', 'name')},
        ),
    ]
