# Generated by Django 2.2.9 on 2020-04-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0004_auto_20200423_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='jogos.Modality'),
        ),
    ]
