# Generated by Django 2.2.9 on 2020-04-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0005_auto_20200424_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages_modality', to='jogos.Modality'),
        ),
        migrations.AlterUniqueTogether(
            name='modality',
            unique_together={('name',)},
        ),
    ]
